# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1830982dd822e9ef2b44e37536001687d89653010a2b7e2a8504f3a85f35adbcb6dddf840086502d4b368dd9c07e085262462d6f76998667fc4fd44d554876c0

test:
  secret_key_base: ee5cf5bb642cbe8dbb9f00b5a95243e4645c55f7cccbb6dbdb102830c372b2edd32b8f6276aa95c713a87224d55e2b8872d12ad3775af4886498786e4129da82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
